### ISSUE TITLE
error in MacOS 10.13.4 

### ISSUE THREAD

**Issue by shankar08** [ammardodin/assistant-cross-validation#8]
When I am trying to run this python, I am getting the following error. I am not an expert in python so I couldn't find why its doing it. Could you advise me a way around for this error.

Traceback (most recent call last):
  File "assistant_cv.py", line 132, in <module>
    validate_with_fold_helper, zip(folds, repeat(data, num_folds)))
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value

**Comment by shankar08** [comment]
Its not there any more.
